// Code generated by table-def-gen. DO NOT EDIT.

package goql

type AccountTableDef struct {
	*SqlableTable
	alias     *string
	CreatedTs *Col[int]
	Id        *Col[int64]
	Type      *Col[string]
	Uuid      *Col[string]
}

var _ Table = &AccountTableDef{}

func newAccountTable() *AccountTableDef {
	tDef := &AccountTableDef{}
	tDef.CreatedTs = NewCol[int]("created_ts", tDef)
	tDef.Id = NewCol[int64]("id", tDef)
	tDef.Type = NewCol[string]("type", tDef)
	tDef.Uuid = NewCol[string]("uuid", tDef)
	tDef.SqlableTable = NewSqlableTable(tDef)
	return tDef
}

var Account = newAccountTable()

func (a *AccountTableDef) TableName() string {
	return "account"
}

func (a *AccountTableDef) Alias() *string {
	return a.alias
}

func (a *AccountTableDef) As(x string) *AccountTableDef {
	newT := newAccountTable()
	newT.alias = &x
	return newT
}

func (a *AccountTableDef) Star() ParametricSql {
	return NewCol[string]("*", a)
}

type ConfigTableDef struct {
	*SqlableTable
	alias      *string
	AccountId  *Col[int64]
	ArchivedTs *Col[int]
	CreatedTs  *Col[int]
	Id         *Col[int64]
	Uuid       *Col[string]
}

var _ Table = &ConfigTableDef{}

func newConfigTable() *ConfigTableDef {
	tDef := &ConfigTableDef{}
	tDef.AccountId = NewCol[int64]("account_id", tDef)
	tDef.ArchivedTs = NewCol[int]("archived_ts", tDef)
	tDef.CreatedTs = NewCol[int]("created_ts", tDef)
	tDef.Id = NewCol[int64]("id", tDef)
	tDef.Uuid = NewCol[string]("uuid", tDef)
	tDef.SqlableTable = NewSqlableTable(tDef)
	return tDef
}

var Config = newConfigTable()

func (a *ConfigTableDef) TableName() string {
	return "config"
}

func (a *ConfigTableDef) Alias() *string {
	return a.alias
}

func (a *ConfigTableDef) As(x string) *ConfigTableDef {
	newT := newConfigTable()
	newT.alias = &x
	return newT
}

func (a *ConfigTableDef) Star() ParametricSql {
	return NewCol[string]("*", a)
}

type ShoppingCartTableDef struct {
	*SqlableTable
	alias      *string
	ArchivedTs *Col[int]
	CreatedTs  *Col[int]
	Id         *Col[int64]
	OwnerId    *Col[int64]
	Uuid       *Col[string]
}

var _ Table = &ShoppingCartTableDef{}

func newShoppingCartTable() *ShoppingCartTableDef {
	tDef := &ShoppingCartTableDef{}
	tDef.ArchivedTs = NewCol[int]("archived_ts", tDef)
	tDef.CreatedTs = NewCol[int]("created_ts", tDef)
	tDef.Id = NewCol[int64]("id", tDef)
	tDef.OwnerId = NewCol[int64]("owner_id", tDef)
	tDef.Uuid = NewCol[string]("uuid", tDef)
	tDef.SqlableTable = NewSqlableTable(tDef)
	return tDef
}

var ShoppingCart = newShoppingCartTable()

func (a *ShoppingCartTableDef) TableName() string {
	return "shopping_cart"
}

func (a *ShoppingCartTableDef) Alias() *string {
	return a.alias
}

func (a *ShoppingCartTableDef) As(x string) *ShoppingCartTableDef {
	newT := newShoppingCartTable()
	newT.alias = &x
	return newT
}

func (a *ShoppingCartTableDef) Star() ParametricSql {
	return NewCol[string]("*", a)
}
