// Code generated by table-def-gen. DO NOT EDIT.

package goql

// dbRelationships is a map representing the relationships between tables in the database,
// indexed by source table, target table, source column -> target column.
var dbRelationships = map[Table]map[Table]map[Column]Column{
	Account: {
		ShoppingCart: map[Column]Column{
			Account.Id: ShoppingCart.OwnerId,
		},
	},
	ShoppingCart: {
		Account: map[Column]Column{
			ShoppingCart.OwnerId: Account.Id,
		},
	},
}