// Code generated by table-def-gen. DO NOT EDIT.

package main

import "github.com/sergiobonfiglio/tomasql"

// dbRelationships is a map representing the relationships between tables in the database,
// indexed by source table, target table, source column -> target column.
var dbRelationships = map[tomasql.Table]map[tomasql.Table]map[tomasql.Column]tomasql.Column{
	Categories: {
		Categories: map[tomasql.Column]tomasql.Column{
			Categories.Id:       Categories.ParentId,
			Categories.ParentId: Categories.Id,
		},
		Products: map[tomasql.Column]tomasql.Column{
			Categories.Id: Products.CategoryId,
		},
	},
	OrderItems: {
		Orders: map[tomasql.Column]tomasql.Column{
			OrderItems.OrderId: Orders.Id,
		},
		Products: map[tomasql.Column]tomasql.Column{
			OrderItems.ProductId: Products.Id,
		},
	},
	Orders: {
		OrderItems: map[tomasql.Column]tomasql.Column{
			Orders.Id: OrderItems.OrderId,
		},
		Users: map[tomasql.Column]tomasql.Column{
			Orders.UserId: Users.Id,
		},
	},
	Products: {
		Categories: map[tomasql.Column]tomasql.Column{
			Products.CategoryId: Categories.Id,
		},
		OrderItems: map[tomasql.Column]tomasql.Column{
			Products.Id: OrderItems.ProductId,
		},
	},
	Users: {
		Orders: map[tomasql.Column]tomasql.Column{
			Users.Id: Orders.UserId,
		},
	},
}
