// Code generated by table-def-gen. DO NOT EDIT.

package main

import (
	"github.com/sergiobonfiglio/tomasql"
	"time"
)

type CategoriesTableDef struct {
	*tomasql.SqlableTable
	alias       *string
	CreatedAt   *tomasql.Col[time.Time]
	Description *tomasql.Col[string]
	Id          *tomasql.Col[int]
	Name        *tomasql.Col[string]
	ParentId    *tomasql.Col[int]
}

var _ tomasql.Table = &CategoriesTableDef{}

func newCategoriesTable() *CategoriesTableDef {
	tDef := &CategoriesTableDef{}
	tDef.CreatedAt = tomasql.NewCol[time.Time]("created_at", tDef)
	tDef.Description = tomasql.NewCol[string]("description", tDef)
	tDef.Id = tomasql.NewCol[int]("id", tDef)
	tDef.Name = tomasql.NewCol[string]("name", tDef)
	tDef.ParentId = tomasql.NewCol[int]("parent_id", tDef)
	tDef.SqlableTable = tomasql.NewSqlableTable(tDef)
	return tDef
}

var Categories = newCategoriesTable()

func (a *CategoriesTableDef) TableName() string {
	return "categories"
}

func (a *CategoriesTableDef) Alias() *string {
	return a.alias
}

func (a *CategoriesTableDef) As(x string) *CategoriesTableDef {
	newT := newCategoriesTable()
	newT.alias = &x
	return newT
}

func (a *CategoriesTableDef) Star() tomasql.ParametricSql {
	return tomasql.NewCol[string]("*", a)
}

type OrderItemsTableDef struct {
	*tomasql.SqlableTable
	alias     *string
	Id        *tomasql.Col[int]
	OrderId   *tomasql.Col[int]
	Price     *tomasql.Col[float64]
	ProductId *tomasql.Col[int]
	Quantity  *tomasql.Col[int]
}

var _ tomasql.Table = &OrderItemsTableDef{}

func newOrderItemsTable() *OrderItemsTableDef {
	tDef := &OrderItemsTableDef{}
	tDef.Id = tomasql.NewCol[int]("id", tDef)
	tDef.OrderId = tomasql.NewCol[int]("order_id", tDef)
	tDef.Price = tomasql.NewCol[float64]("price", tDef)
	tDef.ProductId = tomasql.NewCol[int]("product_id", tDef)
	tDef.Quantity = tomasql.NewCol[int]("quantity", tDef)
	tDef.SqlableTable = tomasql.NewSqlableTable(tDef)
	return tDef
}

var OrderItems = newOrderItemsTable()

func (a *OrderItemsTableDef) TableName() string {
	return "order_items"
}

func (a *OrderItemsTableDef) Alias() *string {
	return a.alias
}

func (a *OrderItemsTableDef) As(x string) *OrderItemsTableDef {
	newT := newOrderItemsTable()
	newT.alias = &x
	return newT
}

func (a *OrderItemsTableDef) Star() tomasql.ParametricSql {
	return tomasql.NewCol[string]("*", a)
}

type OrdersTableDef struct {
	*tomasql.SqlableTable
	alias       *string
	CreatedAt   *tomasql.Col[time.Time]
	Id          *tomasql.Col[int]
	Status      *tomasql.Col[string]
	TotalAmount *tomasql.Col[float64]
	UpdatedAt   *tomasql.Col[time.Time]
	UserId      *tomasql.Col[int]
}

var _ tomasql.Table = &OrdersTableDef{}

func newOrdersTable() *OrdersTableDef {
	tDef := &OrdersTableDef{}
	tDef.CreatedAt = tomasql.NewCol[time.Time]("created_at", tDef)
	tDef.Id = tomasql.NewCol[int]("id", tDef)
	tDef.Status = tomasql.NewCol[string]("status", tDef)
	tDef.TotalAmount = tomasql.NewCol[float64]("total_amount", tDef)
	tDef.UpdatedAt = tomasql.NewCol[time.Time]("updated_at", tDef)
	tDef.UserId = tomasql.NewCol[int]("user_id", tDef)
	tDef.SqlableTable = tomasql.NewSqlableTable(tDef)
	return tDef
}

var Orders = newOrdersTable()

func (a *OrdersTableDef) TableName() string {
	return "orders"
}

func (a *OrdersTableDef) Alias() *string {
	return a.alias
}

func (a *OrdersTableDef) As(x string) *OrdersTableDef {
	newT := newOrdersTable()
	newT.alias = &x
	return newT
}

func (a *OrdersTableDef) Star() tomasql.ParametricSql {
	return tomasql.NewCol[string]("*", a)
}

type ProductsTableDef struct {
	*tomasql.SqlableTable
	alias         *string
	CategoryId    *tomasql.Col[int]
	CreatedAt     *tomasql.Col[time.Time]
	Description   *tomasql.Col[string]
	Id            *tomasql.Col[int]
	Name          *tomasql.Col[string]
	Price         *tomasql.Col[float64]
	StockQuantity *tomasql.Col[int]
	UpdatedAt     *tomasql.Col[time.Time]
}

var _ tomasql.Table = &ProductsTableDef{}

func newProductsTable() *ProductsTableDef {
	tDef := &ProductsTableDef{}
	tDef.CategoryId = tomasql.NewCol[int]("category_id", tDef)
	tDef.CreatedAt = tomasql.NewCol[time.Time]("created_at", tDef)
	tDef.Description = tomasql.NewCol[string]("description", tDef)
	tDef.Id = tomasql.NewCol[int]("id", tDef)
	tDef.Name = tomasql.NewCol[string]("name", tDef)
	tDef.Price = tomasql.NewCol[float64]("price", tDef)
	tDef.StockQuantity = tomasql.NewCol[int]("stock_quantity", tDef)
	tDef.UpdatedAt = tomasql.NewCol[time.Time]("updated_at", tDef)
	tDef.SqlableTable = tomasql.NewSqlableTable(tDef)
	return tDef
}

var Products = newProductsTable()

func (a *ProductsTableDef) TableName() string {
	return "products"
}

func (a *ProductsTableDef) Alias() *string {
	return a.alias
}

func (a *ProductsTableDef) As(x string) *ProductsTableDef {
	newT := newProductsTable()
	newT.alias = &x
	return newT
}

func (a *ProductsTableDef) Star() tomasql.ParametricSql {
	return tomasql.NewCol[string]("*", a)
}

type UsersTableDef struct {
	*tomasql.SqlableTable
	alias     *string
	CreatedAt *tomasql.Col[time.Time]
	Email     *tomasql.Col[string]
	Id        *tomasql.Col[int]
	IsActive  *tomasql.Col[bool]
	Name      *tomasql.Col[string]
	UpdatedAt *tomasql.Col[time.Time]
}

var _ tomasql.Table = &UsersTableDef{}

func newUsersTable() *UsersTableDef {
	tDef := &UsersTableDef{}
	tDef.CreatedAt = tomasql.NewCol[time.Time]("created_at", tDef)
	tDef.Email = tomasql.NewCol[string]("email", tDef)
	tDef.Id = tomasql.NewCol[int]("id", tDef)
	tDef.IsActive = tomasql.NewCol[bool]("is_active", tDef)
	tDef.Name = tomasql.NewCol[string]("name", tDef)
	tDef.UpdatedAt = tomasql.NewCol[time.Time]("updated_at", tDef)
	tDef.SqlableTable = tomasql.NewSqlableTable(tDef)
	return tDef
}

var Users = newUsersTable()

func (a *UsersTableDef) TableName() string {
	return "users"
}

func (a *UsersTableDef) Alias() *string {
	return a.alias
}

func (a *UsersTableDef) As(x string) *UsersTableDef {
	newT := newUsersTable()
	newT.alias = &x
	return newT
}

func (a *UsersTableDef) Star() tomasql.ParametricSql {
	return tomasql.NewCol[string]("*", a)
}
